# -*- coding: utf-8 -*-
"""translation_for_TTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KcsMwheIzhOZmyk0fa3dNDPjwIeMkdXR

### Translation of English to Swahili for East African Users
"""

!pip install googletrans==4.0.0-rc1

from googletrans import Translator

translator = Translator()

text = "Good morning and how have you been"
translated_text = translator.translate(text, src='en', dest='sw')
print(translated_text.text)  # the translation

detected_lang = translator.detect(text)
print(detected_lang.lang)  # Output: 'fr'
